### ISSUE TITLE
Support of different hosts

### ISSUE THREAD

**Issue by nathanfallet** [NozeIO/MicroExpress#10]
There is an HTTP header called `Host`, so it could be great to have a native way to filter host to have different routes depending of them.

For example, you can have a `example.com` domain and filter host to have different routes depending on if we call `example.com` or `api.example.com` (and many more possibilities)

**Comment by nathanfallet** [comment]
Or if this is not possible, I can create multiple express objects listening on different ports (one for each sub domain)

**Comment by helje5** [comment]
Virtual host support, sure! Not as part of _Micro_Express however :-) For more elaborate stuff, I have setup [MacroExpress](https://github.com/Macro-swift/MacroExpress). It's like MicroExpress, but with the intention to be more full features (like Noze.io).

I'm going to try to transfer this issue over there.

It would be good to have a pointer to how Node Express is usually doing the functionality, as I'd like to avoid reinventing API.

**Comment by helje5** [comment]
Looks like GitHub can't transfer issues between orgs. Do you want to recreate the issue in Macro, or I can do that as well. Just let me know!

**Comment by nathanfallet** [comment]
Well let's recreate this issue in MacroExpress. I'm going to switch from Micro to Macro in my package too.
