### ISSUE TITLE
Add a cookie parser middleware

### ISSUE THREAD

**Issue by nathanfallet** [NozeIO/MicroExpress#12]
As it is available with Express.JS with https://github.com/expressjs/cookie-parser and https://github.com/jshttp/cookie, implement it with µExpress too

**Comment by helje5** [comment]
Not as part of _Micro_Express however :-) For more elaborate stuff, I have setup [MacroExpress](https://github.com/Macro-swift/MacroExpress). It's like MicroExpress, but with the intention to be more full featured (like Noze.io).

Macro already has a simple cookie parser, maybe you want to check it out? You can find it over here: [Cookies](https://github.com/Macro-swift/MacroExpress/blob/master/Sources/connect/Cookies.swift#L13).

**Comment by nathanfallet** [comment]
I'm going to take a look, I didn't know about MacroExpress. Thanks!
