### ISSUE TITLE
Potential illegal instruction exception in ServerResponse.send()

### ISSUE THREAD

**Issue by guillaumerose** [NozeIO/MicroExpress#7]
In ServerReponse send(), HTTPServerRequestPart.body can be sent after HTTPServerRequestPart.end, causing an illegal instruction exception.

If an error happens during HTTPServerRequestPart.head, then handleError() will send an end. Then send() continues and tries to send a body. A precondition is then triggered. 

Code: 
https://github.com/NozeIO/MicroExpress/blob/master/Sources/MicroExpress/ServerResponse.swift#L4
https://github.com/apple/swift-nio/blob/master/Sources/NIOHTTP1/HTTPServerProtocolErrorHandler.swift#L65

**Comment by helje5** [comment]
Hm, right.

**Comment by helje5** [comment]
OK, should be fixed in 0.4.6. Thanks for reporting!
