### ISSUE TITLE
Run on device

### ISSUE THREAD

**Issue by krjw** [NozeIO/MicroExpress#9]
First of all: Great work! I like the idea of MicroExpress

I followed the tutorial in the blog, with Xcode 11 and SPM it is really easy to add MicroExpress to the Project. I got it to work in my Simulator but it won't wok on my device. I modified info.plist to allow arbitrary loads.

Do I miss something or could this be an issue of MicroExpress?

Greetings krjw

**Comment by helje5** [comment]
I doubt it is a MicroExpress issue. Did you add "incoming network" to the entitlements? What are you trying to do, run client and server on the same device? Or do you try to connect to it from your mac?

**Comment by krjw** [comment]
How do I add "incoming network" to the entitlements? They changed everything in Xcode 11. I try to run a server on my old iPhone which is connected via WLAN and I try to access it from my browser via the local IP. Thanks!

**Comment by helje5** [comment]
Can't find it either, might not be necessary on iOS.
What are the precise errors you are getting on either side?
Are you binding NIO to the WAN or just localhost? What does "Server running on" say?

For my own reference: http://www.alwaysrightinstitute.com/nio-on-the-client/

**Comment by krjw** [comment]
I am only getting "Failed to open page" in my browser.
I changed the port: Server running on: [IPv6]::1/::1:8080
I don't manually bind to anything I use the code in the tutorial

```
        let app = Express()

        app.get("/") { req, res, next in
          res.send("Hello World")
        }
        
        Thread.detachNewThread {
            app.listen(8080)
        }
```

I am very grateful that you help me! Thank you!

**Comment by helje5** [comment]
You are binding to just the local address `[IPv6]::1/::1:8080`, you need to bind to an address reachable by your Mac. If I read the code right:
```
  open func listen(_ port    : Int    = 1337,
                   _ host    : String = "localhost", // <= the default in Express.swift
                   _ backlog : Int    = 256)
```
You would need to call it like `listen("*.*.*.*", 8080)` or sth like that. Don't remember what the wildcard string representation is.

**Comment by helje5** [comment]
0.0.0.0 seems to be the wildcard IPv4 string

**Comment by krjw** [comment]
Yeah it works thank you very much!! In Simulator this fails though...
